/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketing.system.client;

import javax.swing.JOptionPane;

/**
 *
 * @author ferdi
 */
public class FormDeskripsiAcara extends javax.swing.JFrame {

    /**
     * Creates new form FormDeskripsiAcara
     */
    public FormDeskripsiAcara() {
        initComponents();
    }
    
    public FormDeskripsiAcara(FormAcara p, Acara a) {
        initComponents();
        acaraPilih = a;
        parent = p;
        
        jLabelNamaAcara.setText(a.getNama());
        jTextFieldDeskripsi.setText(a.getDeskripsi());
        jumlahTiket = (int) jSpinnerJumlah.getValue();
        jLabelHarga.setText(String.valueOf(jumlahTiket*acaraPilih.getHarga()));
    }
    Acara acaraPilih;
    FormAcara parent;
    int jumlahTiket;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNama2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSpinnerJumlah = new javax.swing.JSpinner();
        jLabelNama3 = new javax.swing.JLabel();
        jLabelNama4 = new javax.swing.JLabel();
        jLabelNama5 = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jTextFieldDeskripsi = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabelNamaAcara = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1067, 592));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jLabelNama2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelNama2.setText("Pesan :");

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reservasi");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jSpinnerJumlah.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jSpinnerJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinnerJumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerJumlahStateChanged(evt);
            }
        });
        jSpinnerJumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinnerJumlahMouseClicked(evt);
            }
        });

        jLabelNama3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelNama3.setText("Pax");

        jLabelNama4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelNama4.setText("Rp");

        jLabelNama5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelNama5.setText("Total :");

        jLabelHarga.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelHarga.setText("Rp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabelNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSpinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelNama3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNama4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(jLabelNama5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama2)
                    .addComponent(jSpinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama4)
                    .addComponent(jLabelHarga))
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(83, Short.MAX_VALUE)
                    .addComponent(jLabelNama5)
                    .addGap(64, 64, 64)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 280, 600, 184);

        jTextFieldDeskripsi.setEditable(false);
        jTextFieldDeskripsi.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDeskripsi.setText("DESKRIPSI");
        jTextFieldDeskripsi.setCaretColor(new java.awt.Color(0, 51, 51));
        jTextFieldDeskripsi.setMaximumSize(new java.awt.Dimension(132, 574));
        jTextFieldDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDeskripsiActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDeskripsi);
        jTextFieldDeskripsi.setBounds(210, 140, 598, 132);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 153));

        jLabelNamaAcara.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabelNamaAcara.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNamaAcara.setText("DESKRIPSI ACARA");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabelNamaAcara)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelNamaAcara)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1070, 127);

        jButtonBack.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(30, 440, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeskripsiActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try
        {
            jumlahTiket = (int) jSpinnerJumlah.getValue();
            NotaAcara na = tambahNotaAcara(parent.idUser, acaraPilih.getId(), jumlahTiket);
            if(na.getHarga()!=0){
                JOptionPane.showMessageDialog(this, "   BERHASIL    "
                    + "\n No. Transaksi:            "+na.getId()
                    + "\n Username:                 "+na.getUser().getUsername()
                    + "\n Nama Acara:               "+na.getAcara().getNama()
                    + "\n Tanggal Acara:            "+na.getAcara().getTanggalAcara()
                    + "\n Lokasi:                   "+na.getAcara().getLokasi()
                    + "\n Jumlah Tiket:             "+na.getJumlah()
                    + "\n Total Harga:              "+na.getHarga()
                    + "\n Tanggal Transaksi:        "+na.getTanggalTransaksi());
            }
            else {
                JOptionPane.showMessageDialog(this, "GAGAL. SALDO TIDAK MEMENUHI");
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "GAGAL. ERROR: "+ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jSpinnerJumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerJumlahMouseClicked
        jumlahTiket = (int) jSpinnerJumlah.getValue();
        jLabelHarga.setText(String.valueOf(jumlahTiket*acaraPilih.getHarga()));
    }//GEN-LAST:event_jSpinnerJumlahMouseClicked

    private void jSpinnerJumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerJumlahStateChanged
        jumlahTiket = (int) jSpinnerJumlah.getValue();
        jLabelHarga.setText(String.valueOf(jumlahTiket*acaraPilih.getHarga()));
    }//GEN-LAST:event_jSpinnerJumlahStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDeskripsiAcara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDeskripsiAcara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDeskripsiAcara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDeskripsiAcara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDeskripsiAcara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelNama2;
    private javax.swing.JLabel jLabelNama3;
    private javax.swing.JLabel jLabelNama4;
    private javax.swing.JLabel jLabelNama5;
    private javax.swing.JLabel jLabelNamaAcara;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerJumlah;
    private javax.swing.JTextField jTextFieldDeskripsi;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

    private static NotaAcara tambahNotaAcara(int idUser, int idAcara, int jumlah) {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.tambahNotaAcara(idUser, idAcara, jumlah);
    }
}
