/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ticketing.system.client;
    
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Luky
 */
public class FormAcara extends javax.swing.JPanel {

    /**
     * Creates new form FormAcara
     */
    public FormAcara() {
        initComponents();
    }
    public FormAcara(DashBoard p,int id) {
        this();
        parent = p;
        idUser = id;
        RefreshTable();
    }
    DashBoard parent;
    int idUser;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelHasil = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldTanggal = new javax.swing.JTextField();
        jTextFieldLokasi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonDeskripsi = new javax.swing.JButton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Lokasi", "Tanggal Acara", "Harga (Rp)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelHasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelHasil);
        if (jTabelHasil.getColumnModel().getColumnCount() > 0) {
            jTabelHasil.getColumnModel().getColumn(0).setResizable(false);
            jTabelHasil.getColumnModel().getColumn(1).setResizable(false);
            jTabelHasil.getColumnModel().getColumn(2).setResizable(false);
            jTabelHasil.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 140, 760, 505);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nama :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 160, 80, 24);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Lokasi :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 220, 90, 24);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Tanggal Acara :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 280, 150, 24);

        jTextFieldNama.setEditable(false);
        jTextFieldNama.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldNama);
        jTextFieldNama.setBounds(210, 160, 220, 21);

        jTextFieldTanggal.setEditable(false);
        jTextFieldTanggal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTanggal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldTanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldTanggal);
        jTextFieldTanggal.setBounds(210, 280, 220, 21);

        jTextFieldLokasi.setEditable(false);
        jTextFieldLokasi.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldLokasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldLokasi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextFieldLokasi.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldLokasi);
        jTextFieldLokasi.setBounds(210, 220, 220, 21);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Harga :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 350, 80, 24);

        jTextFieldHarga.setEditable(false);
        jTextFieldHarga.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHarga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextFieldHarga);
        jTextFieldHarga.setBounds(210, 350, 220, 21);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Rp");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 350, 40, 24);

        jButtonDeskripsi.setBackground(new java.awt.Color(0, 51, 51));
        jButtonDeskripsi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDeskripsi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeskripsi.setText("Lihat Deskripsi");
        jButtonDeskripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeskripsiMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonDeskripsi);
        jButtonDeskripsi.setBounds(40, 530, 390, 80);

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 102, 153));
        kGradientPanel3.setkTransparentControls(false);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ACARA");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(jLabel8)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(kGradientPanel3);
        kGradientPanel3.setBounds(0, 0, 1230, 127);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelHasilMouseClicked
        JTable klik = (JTable) evt.getSource();
        int row = klik.getSelectedRow();
        
        jTextFieldNama.setText(klik.getValueAt(row, 0).toString());
        jTextFieldLokasi.setText(klik.getValueAt(row, 1).toString());
        jTextFieldTanggal.setText(klik.getValueAt(row, 2).toString());
        jTextFieldHarga.setText(klik.getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_jTabelHasilMouseClicked

    private void jButtonDeskripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeskripsiMouseClicked
        Acara acaraPilih = getAcaraByNama(jTextFieldNama.getText());
        FormDeskripsiAcara form = new FormDeskripsiAcara(this, acaraPilih);
        form.show();
    }//GEN-LAST:event_jButtonDeskripsiMouseClicked

    private void RefreshTable()
    {
        jTabelHasil.removeAll();
        DefaultTableModel model = (DefaultTableModel) jTabelHasil.getModel();
        model.setRowCount(0);
        Object[] rowData=new Object[4];
        java.util.List<ticketing.system.client.Acara> listAcara = getAcara();
        
        for ( ticketing.system.client.Acara obj : listAcara)
        {
            if (obj instanceof ticketing.system.client.Acara)
            {
                ticketing.system.client.Acara tampung = (ticketing.system.client.Acara)obj;
                rowData[0]=tampung.getNama();                
                rowData[1]=tampung.getLokasi();
                rowData[2]=tampung.getTanggalAcara();
                rowData[3]=tampung.getHarga();
                model.addRow(rowData);
            }
        }
        resizeColumnWidth(jTabelHasil);
    }
    
    public void resizeColumnWidth(JTable table) {
        table.getColumnModel().getColumn(0).setMaxWidth(125);
        table.getColumnModel().getColumn(1).setMaxWidth(125);
        table.getColumnModel().getColumn(2).setMaxWidth(125);
        table.getColumnModel().getColumn(3).setMaxWidth(125);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeskripsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelHasil;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldLokasi;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldTanggal;
    private keeptoo.KGradientPanel kGradientPanel3;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<ticketing.system.client.Acara> getAcara() {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.getAcara();
    }

    private static Acara getAcaraByNama(java.lang.String nama) {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.getAcaraByNama(nama);
    }

    

    

}
