/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketing.system.client;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FormSlotParkir extends javax.swing.JFrame {

    /**
     * Creates new form FormSlotParkir
     */
    FormParkir parent;
    Parkir parkir;
    java.util.List<ticketing.system.client.SlotParkir> listSlotParkir;
    java.util.List<ticketing.system.client.JamParkir> listJamParkir;
    SlotParkir selectedSlotParkir;
    public FormSlotParkir() {
        initComponents();        
    }
    public FormSlotParkir(FormParkir p, Parkir selectedParkir) {
        this();
        parent = p;
        parkir = selectedParkir; 
        RefreshTable();
        RefreshJamParkir();                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelParkir = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldKode = new javax.swing.JTextField();
        jTextFieldHarga = new javax.swing.JTextField();
        jButtonBook = new javax.swing.JButton();
        jComboBoxJamParkir = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(966, 469));
        jPanel1.setLayout(null);

        jTabelParkir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode", "Harga"
            }
        ));
        jTabelParkir.setRowHeight(40);
        jTabelParkir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelParkirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelParkir);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(18, 5, 452, 402);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Tanggal:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 140, 76, 24);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Kode :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 60, 58, 24);

        jTextFieldKode.setEnabled(false);
        jPanel1.add(jTextFieldKode);
        jTextFieldKode.setBounds(620, 60, 150, 29);

        jTextFieldHarga.setEnabled(false);
        jPanel1.add(jTextFieldHarga);
        jTextFieldHarga.setBounds(620, 100, 150, 29);

        jButtonBook.setBackground(new java.awt.Color(0, 51, 51));
        jButtonBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBook.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBook.setText("Book");
        jButtonBook.setEnabled(false);
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBook);
        jButtonBook.setBounds(580, 260, 90, 33);

        jComboBoxJamParkir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJamParkirItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxJamParkir);
        jComboBoxJamParkir.setBounds(620, 180, 150, 29);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Jam Parkir :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 180, 105, 24);

        jDateChooser1.setDate(new java.util.Date());
        jDateChooser1.setMinSelectableDate(new java.util.Date());
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(620, 140, 150, 29);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Harga:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(530, 100, 54, 24);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabelParkirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelParkirMouseClicked
        JTable klik = (JTable) evt.getSource();
        int row = klik.getSelectedRow();

        jTextFieldKode.setText(klik.getValueAt(row, 0).toString());
        jTextFieldHarga.setText(klik.getValueAt(row, 1).toString());

        selectedSlotParkir = listSlotParkir.get(row);
        refreshButtonBook();
    }//GEN-LAST:event_jTabelParkirMouseClicked

    private void RefreshTable()
    {
        listSlotParkir = getSlotParkir(parkir.id);
        
        jTabelParkir.removeAll();
        
        DefaultTableModel model = (DefaultTableModel) jTabelParkir.getModel();
        model.setRowCount(0);
        Object[] rowData=new Object[2];
        
        for ( ticketing.system.client.SlotParkir obj : listSlotParkir)
        {            
            ticketing.system.client.SlotParkir tampung = (ticketing.system.client.SlotParkir)obj;
            rowData[0]=tampung.getKode();                
            rowData[1]=tampung.getHarga();                            
            model.addRow(rowData);
        }
    }
    private void RefreshJamParkir(){
        jComboBoxJamParkir.removeAllItems();
        listJamParkir = getJamParkir();
        for(JamParkir jp : listJamParkir){
            jComboBoxJamParkir.addItem(jp.jamMulai + " - " + jp.jamSelesai);
        }
    }
    private void refreshButtonBook(){
        if(selectedSlotParkir != null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            if(cekKetersediaanSlotParkir(selectedSlotParkir.getParkir().getId(),selectedSlotParkir.getKode(),listJamParkir.get(jComboBoxJamParkir.getSelectedIndex()).getId(),sdf.format(jDateChooser1.getDate()))){
                jButtonBook.setEnabled(true);
            }
            else{
                jButtonBook.setEnabled(false);
            }
        
        }
        
    }
    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        // TODO add your handling code here:        
        if(JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin memesan?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            if(tambahNotaParkir(parent.parent.idUserLogin, sdf.format(jDateChooser1.getDate()), parkir.getId(), selectedSlotParkir.getKode(), listJamParkir.get(jComboBoxJamParkir.getSelectedIndex()).getId())){
                JOptionPane.showMessageDialog(parent, "Booking berhasil");
                parent.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(parent, "Booking gagal");
            }
        }
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:       
        refreshButtonBook();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jComboBoxJamParkirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJamParkirItemStateChanged
        // TODO add your handling code here:
        refreshButtonBook();
    }//GEN-LAST:event_jComboBoxJamParkirItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSlotParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSlotParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSlotParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSlotParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSlotParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBook;
    private javax.swing.JComboBox<String> jComboBoxJamParkir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelParkir;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldKode;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<ticketing.system.client.SlotParkir> getSlotParkir(int idParkir) {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.getSlotParkir(idParkir);
    }

    private static java.util.List<ticketing.system.client.JamParkir> getJamParkir() {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.getJamParkir();
    }

    private static Boolean cekKetersediaanSlotParkir(int parkirId, java.lang.String kode, int jamParkirId, java.lang.String tanggalBooking) {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.cekKetersediaanSlotParkir(parkirId, kode, jamParkirId, tanggalBooking);
    }

    private static boolean tambahNotaParkir(int idUser, java.lang.String tanggalBooking, int parkirId, java.lang.String slotParkirKode, int jamParkirId) {
        ticketing.system.client.TicketingService_Service service = new ticketing.system.client.TicketingService_Service();
        ticketing.system.client.TicketingService port = service.getTicketingServicePort();
        return port.tambahNotaParkir(idUser, tanggalBooking, parkirId, slotParkirKode, jamParkirId);
    }




}
